name: exaile-testimg CI

on:
  push:
  pull_request:
  schedule:
    - cron: '41 5 * * *'
  workflow_dispatch:  # Allow running manually

jobs:
  build:
    strategy:
      matrix:
        include:
          ## These are generally the oldest and newest releases that contain
          ## Python >= 3.10 and are still maintained
          # https://endoflife.date/debian
          # https://packages.debian.org/bookworm/python3 -> 3.11
          - name: debian
            version: 12
          - name: debian
            version: stable
          # https://endoflife.date/fedora
          # https://mdapi.fedoraproject.org/f40/pkg/python3 -> 3.12
          - name: fedora
            version: 40
          - name: fedora
            version: latest
          # https://endoflife.date/ubuntu
          # https://packages.ubuntu.com/jammy/python3 -> 3.10
          - name: ubuntu
            version: 22.04
          - name: ubuntu
            version: rolling
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/exaile-testimg:${{ matrix.name }}-${{ matrix.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login
        run: printf '%s' '${{ secrets.GITHUB_TOKEN }}' | docker login ghcr.io -u '${{ github.actor }}' --password-stdin
      - name: Build
        run: >
          docker buildx build
          -f 'Dockerfile.${{ matrix.name }}'
          -t "$IMAGE"
          --build-arg 'VERSION=${{ matrix.version }}'
          .
      - name: History
        run: docker history "$IMAGE"
      - name: Push
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/master'
        run: docker push "$IMAGE"
